# Generated by Django 5.0.3 on 2024-04-10 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('trainID', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=30)),
                ('destination', models.TextField()),
                ('depart', models.CharField(max_length=30)),
                ('plan', models.CharField(max_length=30)),
            ],
        ),
    ]
